### ISSUE TITLE
name 'str_idx' is not defined

### ISSUE THREAD

**Issue by nazmiasri95** [DevconX/Malaya#6]
```
/usr/local/lib/python3.6/dist-packages/malaya/pos_entities.py in predict(self, string)
     22     def predict(self,string):
     23         assert (isinstance(string, str)), "input must be a string"
---> 24         return self.__predict(string,self.sess,self.nodes)
     25 
     26 def get_entity_char(string,sess,model):

/usr/local/lib/python3.6/dist-packages/malaya/pos_entities.py in get_entity_char(string, sess, model)
     25 
     26 def get_entity_char(string,sess,model):
---> 27     batch_x = str_idx([process_word_pos_entities(w) for w in string.split()],model['char2idx'],0)
     28     logits, logits_pos = sess.run([tf.argmax(model['logits'],1),tf.argmax(model['logits_pos'],1)],feed_dict={model['X']:batch_x})
     29     results = []

NameError: name 'str_idx' is not defined
```

Face this error when running: 
```
### Demo: entities-pos
for i in available_models:
    print('Testing %s model'%(i))
    print(malaya.deep_pos_entities(i).predict(string))
    print()
```

**Comment by huseinzol05** [comment]
Fixed it, forgot that I renamed the function last second before commit v0.6, I wonder why I don't test that code first.

https://github.com/DevconX/Malaya/commit/597c9e25a3760f3a63996b3147ab803c0d80de91

Bumped into v0.6.0.2 for PIP package, thanks!

**Comment by huseinzol05** [comment]
and I am really suggest you to not use `malaya.deep_pos_entities`, it pretty much deprecated, stated in [wiki](https://github.com/DevconX/Malaya/wiki/POS-Entities-Recognition)

**Comment by nazmiasri95** [comment]
Noted that @huseinzol05 . 
I'm currently trying to understand how do you build this package (and testing it), will try to contribute on something since this gonna be very useful later.
