### ISSUE TITLE
Error module 'pandas.core.computation' has no attribute 'expressions' when import malaya

### ISSUE THREAD

**Issue by amzar96** [DevconX/Malaya#7]
I got this error `AttributeError: module 'pandas.core.computation' has no attribute 'expressions'` when import malaya in my code.

Version : 
**Pandas 0.23.4
Malaya 0.6.0.2**

How to fix this issue?

Machine specs : https://imgur.com/a/PgaE4kD

**Comment by huseinzol05** [comment]
I guess this is `Dask` issue, solved when following this [issue](https://github.com/tflearn/tflearn/issues/766).
