### ISSUE TITLE
We used these data in our project

### ISSUE THREAD

**Issue by cedrickchee** [DevconX/Malaya#9]
Hi Husein or Sani,

This is not a bug or issue report. I hope your day is going well. First of all, I would like to say that this is a great project. Thank you for providing us the datasets and a decent baseline for benchmark.

Regarding this:

https://github.com/DevconX/Malaya/wiki/Dataset#disclaimer
> Please at least email us first before distributing these data. Remember all these hard workings we want to give it for free.

Instead of emailing you, I prefer to inform you here. We used these data in our project: 

https://forums.fast.ai/t/ulmfit-for-malay-project/29677?u=cedric

Do let me know if you have any questions.

**Comment by huseinzol05** [comment]
Yah sure, totally!

And, I want to import your notebook into Malaya, that is so cool!

**Comment by cedrickchee** [comment]
OK, you can go ahead!
